In [5]:
import pandas as pd

# 1 - Abrir o arquivo Excel em um DataFrame
caminho_arquivo = r'C:\Users\vinic\OneDrive\Área de Trabalho\Gabrielly\Curso Python - Coder House\Aulas e Exercícios\best-selling game consoles.xlsx'
df = pd.read_excel(caminho_arquivo, sheet_name='consoles')

# 2 - Substituir a palavra "NES" por "Nitendinho" no nome dos consoles e deixar todos os nomes em maiúsculas
df['Console Name'] = df['Console Name'].str.replace('NES', 'Nitendinho', case=False)
df['Console Name'] = df['Console Name'].str.upper()

# 3 - Filtrar os consoles com data de lançamento depois de 2010
df = df[df['Released Year'] > 2010]

# 4 - Descrever a base, exibir informações e substituir valores faltantes
df_describe = df.describe(include='all')  # Exibe as estatísticas descritivas
df_info = df.info()  # Exibe informações sobre o DataFrame
df.fillna('missing', inplace=True)  # Substitui valores ausentes por 'missing'

# 5 - Filtrar consoles descontinuados a menos de 2 anos da data de lançamento
df['Lifespan'] = df['Discontinuation Year'] - df['Released Year']
df_filtered = df[df['Lifespan'] < 2]

# Exibir o DataFrame final com os filtros aplicados
display(df_filtered)

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 2 to 35
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Console Name          10 non-null     object
 1   Type                  10 non-null     object
 2   Company               10 non-null     object
 3   Released Year         10 non-null     int64
 4   Discontinuation Year  10 non-null     int64
 5   Units sold (million)  10 non-null     float64
 6   Remarks               3 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 640.0+ bytes

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks,Lifespan
2,NINTENDO SWITCH,Hybrid,Nintendo,2017,0,122.55,missing,-2017
5,PLAYSTATION 4,Home,Sony,2013,0,117.20,missing,-2013
19,PLAYSTATION 5,Home,Sony,2020,0,30.00,missing,-2020
23,XBOX SERIES X/S,Home,Microsoft,2020,0,18.50,Approximately around 18.5 million,-2020
33,SUPER NITENDINHO CLASSIC EDITION,Dedicated,Nintendo,2017,2018,5.28,missing,1